# -*- coding: utf-8 -*-
"""examples.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1veNNMUkAW7TJlphcW_KHtb3IsjAtBgLJ

# Find the reverse of the string using stack
"""

string="meftun akarsu CMF1"

def create():
  stack=[]
  return stack

def push(stack,item):
  stack.append(item)

def pop(stack):
  return stack.pop()

def findReverse(string):
  strr=""
  stack = create()

  for i in range(len(string)):
    push(stack,string[len(string)-1-i])
    
  for i in stack:
    strr+=i
  return strr

findReverse(string)

"""# Use Python List like Stack and Queue"""

stack = ["meftun","akarsu","cmf1"]

stack.append("CYC")
print(stack)
stack.pop()# last out
print(stack)

"""# Create Queue with list and deque"""

from collections import deque

queue=deque(["meftun","akarsu","cmf1"])
print(queue)
queue.insert(0,"pazartesi")
print(queue)

"""# 2 stack 1 Queue"""

class Queue2Stack:
  def __init__(self):
    """
    initilizaze 2 stack
    """
    self.stack1=[]
    self.stack2=[]

  def enqueue(self,item):
    """
    add item stack
    """
    self.stack1.append(item)

  def dequeue(self):
    """
    sent item from stack1 to stack2 doing pop 
    """
    if not self.stack2:
      while len(self.stack1)>0:
        self.stack2.append(self.stack1.pop())

    return self.stack2.pop()

queue=Queue2Stack()
queue.enqueue("1")
queue.enqueue("2")
queue.enqueue("3")

print(queue.dequeue())
print(queue.dequeue())
print(queue.dequeue())